version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "hello circle"

workflows:
  workflow:
    jobs:
      - build:
          name: spec
      - build:
          name: test
      - build:
          name: a/test
      - build:
          name: a/spec